name: Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    container:
     image: honeygain/honeygain:latest

    steps:
      - run: |
          sudo apt-get -y update
          sudo apt-get -y install git
          git config --global --add safe.directory $PWD
          cp /app/honeygain /usr/lib/libhg.so* /usr/lib/libmsquic.so.2* .

      - uses: actions/checkout@v4

      - name: Git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Data"
            git push
          fi
